### ISSUE TITLE
Switching contexts code from readme is missing

### ISSUE THREAD

**Issue by gabrieloc** [muckSponge/UnityAsync#11]
Hi, the readme references `Await.UnitySyncContext` but nothing seems to resemble this API on master. Was there a rename?

**Comment by muckSponge** [comment]
It's [definitely there](https://github.com/muckSponge/UnityAsync/blob/a26e67546d36918d6e4b37a8a9b55699c8036605/UnityAsync/Assets/UnityAsync/Await/Await.cs#L17).

**Comment by gabrieloc** [comment]
Apologies, I had managed to clone from [Bitbucket](https://bitbucket.org/muckSponge/unityasync.git), which hasn't been pushed to since 2017.
