### ISSUE TITLE
Latest Update not compatible with Assembly Definition Files

### ISSUE THREAD

**Issue by cfoulston** [muckSponge/UnityAsync#3]
Specifically after this refactoring: https://github.com/muckSponge/UnityAsync/commit/5430f351c9a06377d61018a946dcbb24c55418b4

`Extensions` class is internal, when the library is referenced using asmdefs, `Extensions` class is hidden. Which results in this error:

``'WaitForFrames' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'WaitForFrames' could be found (are you missing a using directive or an assembly reference?)``

Solution is to Make `Extensions` class public. This also means that other classes need to be made public as well:

`SynchronizationContextAwaiter`
`IEnumeratorAwaiter`
`YieldInstructionAwaiter`

**Comment by muckSponge** [comment]
I've implemented this solution and added an asmdef file. I'll close this now but if you experience any problems with it, happy to open it again.
