### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by denisw** [muckSponge/UnityAsync#6]
I didn't find any description on how to actually use this library within a Unity project. It's not in the Asset Store, right? Is the idea to just copy-paste the contents of this repository into the project?

**Comment by muckSponge** [comment]
Yeah, basically. Anything in the assets folder should be placed into your project's asset folder (you can just download it as a zip and extract it to your project folder).

It might be a good idea for me to create a unitypackage file in the releases section to make it easier.

**Comment by denisw** [comment]
Thank you for the quick answer! I think a Unity package file and/or a mention in the README how to integrate this would go a long way to make this library more accessible.

**Comment by muckSponge** [comment]
Updated the README and provided a unitypackage in the latest release (and will do so from now on).
