### ISSUE TITLE
How to await an AsyncOperation?

### ISSUE THREAD

**Issue by tonimarquez84** [muckSponge/UnityAsync#9]
I'm trying to load an scene aynchronous with await instead of using yield statement of coroutines. Is there any way to do it with this library?

**Comment by muckSponge** [comment]
Should be as simple as awaiting the `AsyncOperation` from the code block that produces it:

```c#
using UnityAsync;

...

var t = Time.realTimeSinceStartup;
await SceneManager.LoadSceneAsync(...);
Debug.Log($"Scene loaded in {Time.realTimeSinceStartup - t}s!");
```

Haven't tested the above code but that's the gist of it. Happy to provide a tested example if it doesn't work for you, just let me know.

**Comment by tonimarquez84** [comment]
It works, thank you!
